version: "3"
services:
  db:
    container_name: mysql
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board_app
    ports:
      - "8884:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mysql?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db